spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community_service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${COMMUNITY_DB_PASSWORD:root}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3s

logging:
  level:
    xxqqyyy.community: INFO
    org.mybatis: DEBUG

