-- 社区服务系统数据库初始化脚本（表结构）
-- 数据库：MySQL 8.x
-- 说明：不使用外键，关联一致性由应用层事务与校验保证

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(64) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码（BCrypt）',
    nickname VARCHAR(64) NOT NULL COMMENT '昵称',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    email VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    org_id BIGINT NOT NULL COMMENT '所属组织ID',
    must_change_password TINYINT NOT NULL DEFAULT 0 COMMENT '是否首次改密：1是，0否',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    role_code VARCHAR(64) NOT NULL COMMENT '角色编码',
    role_name VARCHAR(64) NOT NULL COMMENT '角色名称',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    parent_role_id BIGINT DEFAULT NULL COMMENT '父角色ID',
    allow_create_child TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许创建下级角色：1是，0否',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序值',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统角色表';

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    permission_code VARCHAR(128) NOT NULL COMMENT '权限编码',
    permission_name VARCHAR(128) NOT NULL COMMENT '权限名称',
    permission_type VARCHAR(32) NOT NULL COMMENT '权限类型：MENU/BUTTON/API',
    parent_id BIGINT DEFAULT NULL COMMENT '父权限ID',
    path VARCHAR(255) DEFAULT NULL COMMENT '资源路径',
    method VARCHAR(16) DEFAULT NULL COMMENT 'HTTP方法',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序值',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统权限表';

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关联表';

CREATE TABLE IF NOT EXISTS sys_role_scope (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    scope_type VARCHAR(32) NOT NULL COMMENT '数据范围类型：ALL/STREET/COMMUNITY/COMPLEX/PROPERTY_COMPANY/CUSTOM/SELF',
    scope_ref_id BIGINT DEFAULT NULL COMMENT '数据范围引用ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色数据范围关联表';

CREATE TABLE IF NOT EXISTS sys_org (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    parent_id BIGINT DEFAULT NULL COMMENT '父组织ID',
    org_code VARCHAR(64) NOT NULL COMMENT '组织编码',
    org_name VARCHAR(128) NOT NULL COMMENT '组织名称',
    org_type VARCHAR(32) NOT NULL COMMENT '组织类型：STREET/COMMUNITY/COMPLEX/PROPERTY_COMPANY/DEPARTMENT',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序值',
    ancestor_path VARCHAR(512) NOT NULL DEFAULT '/' COMMENT '祖先路径，例如/1/3/',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织表';

CREATE TABLE IF NOT EXISTS sys_dict_type (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    dict_code VARCHAR(64) NOT NULL COMMENT '字典编码',
    dict_name VARCHAR(128) NOT NULL COMMENT '字典名称',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典类型表';

CREATE TABLE IF NOT EXISTS sys_dict_data (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    dict_type_code VARCHAR(64) NOT NULL COMMENT '字典类型编码',
    dict_label VARCHAR(128) NOT NULL COMMENT '字典显示文本',
    dict_value VARCHAR(128) NOT NULL COMMENT '字典值',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序值',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典数据表';

CREATE TABLE IF NOT EXISTS biz_complex_property_rel (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    complex_org_id BIGINT NOT NULL COMMENT '小区组织ID',
    property_company_org_id BIGINT NOT NULL COMMENT '物业公司组织ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小区-物业服务关系表';

CREATE TABLE IF NOT EXISTS biz_resident_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '居民用户ID',
    community_org_id BIGINT NOT NULL COMMENT '社区组织ID',
    complex_org_id BIGINT NOT NULL COMMENT '小区组织ID',
    room_no VARCHAR(64) DEFAULT NULL COMMENT '房号',
    emergency_contact VARCHAR(64) DEFAULT NULL COMMENT '紧急联系人',
    emergency_phone VARCHAR(20) DEFAULT NULL COMMENT '紧急联系电话',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='居民档案表';

CREATE TABLE IF NOT EXISTS biz_file_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_id BIGINT DEFAULT NULL COMMENT '业务ID',
    storage_type VARCHAR(32) NOT NULL DEFAULT 'LOCAL' COMMENT '存储类型：LOCAL/MINIO',
    file_name VARCHAR(255) NOT NULL COMMENT '系统文件名',
    origin_file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_path VARCHAR(512) NOT NULL COMMENT '文件路径',
    file_size BIGINT NOT NULL COMMENT '文件大小（字节）',
    content_type VARCHAR(128) DEFAULT NULL COMMENT '文件类型',
    uploader_id BIGINT DEFAULT NULL COMMENT '上传人ID',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件信息表';

CREATE TABLE IF NOT EXISTS log_login (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    username VARCHAR(64) DEFAULT NULL COMMENT '用户名',
    success_flag TINYINT NOT NULL COMMENT '登录结果：1成功，0失败',
    message VARCHAR(255) DEFAULT NULL COMMENT '登录结果说明',
    ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
    user_agent VARCHAR(512) DEFAULT NULL COMMENT '客户端信息',
    login_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';

CREATE TABLE IF NOT EXISTS log_operation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    username VARCHAR(64) DEFAULT NULL COMMENT '操作人用户名',
    operation_module VARCHAR(64) NOT NULL COMMENT '操作模块',
    operation_type VARCHAR(64) NOT NULL COMMENT '操作类型',
    request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求URI',
    request_method VARCHAR(16) DEFAULT NULL COMMENT '请求方法',
    request_body TEXT COMMENT '请求摘要',
    response_body TEXT COMMENT '响应摘要',
    success_flag TINYINT NOT NULL COMMENT '执行结果：1成功，0失败',
    error_message VARCHAR(512) DEFAULT NULL COMMENT '错误信息',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT '链路追踪ID',
    operation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS biz_notice (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    notice_type VARCHAR(32) NOT NULL COMMENT '公告类型：STREET_COMMUNITY/PROPERTY',
    title VARCHAR(200) NOT NULL COMMENT '公告标题',
    content TEXT NOT NULL COMMENT '公告内容',
    cover_file_id BIGINT DEFAULT NULL COMMENT '封面文件ID',
    attachment_json TEXT COMMENT '附件信息JSON',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '公告状态：DRAFT/PUBLISHED/RECALLED',
    top_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶：1是，0否',
    publisher_org_id BIGINT NOT NULL COMMENT '发布组织ID',
    publish_time DATETIME DEFAULT NULL COMMENT '发布时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告主表';

CREATE TABLE IF NOT EXISTS biz_notice_scope (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    notice_id BIGINT NOT NULL COMMENT '公告ID',
    scope_type VARCHAR(32) NOT NULL COMMENT '范围类型：STREET/COMMUNITY/COMPLEX/PROPERTY_COMPANY/CUSTOM/ALL',
    scope_ref_id BIGINT NOT NULL COMMENT '范围引用组织ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告可见范围表';

CREATE TABLE IF NOT EXISTS biz_activity (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    title VARCHAR(200) NOT NULL COMMENT '活动标题',
    content TEXT NOT NULL COMMENT '活动内容',
    cover_file_id BIGINT DEFAULT NULL COMMENT '封面文件ID',
    attachment_json TEXT COMMENT '附件信息JSON',
    activity_start_time DATETIME NOT NULL COMMENT '活动开始时间',
    activity_end_time DATETIME NOT NULL COMMENT '活动结束时间',
    signup_start_time DATETIME NOT NULL COMMENT '报名开始时间',
    signup_end_time DATETIME NOT NULL COMMENT '报名截止时间',
    location VARCHAR(255) NOT NULL COMMENT '活动地点',
    max_participants INT NOT NULL COMMENT '人数上限',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '活动状态：DRAFT/PUBLISHED/RECALLED/FINISHED',
    publisher_org_id BIGINT NOT NULL COMMENT '发布组织ID',
    publish_time DATETIME DEFAULT NULL COMMENT '发布时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动主表';

CREATE TABLE IF NOT EXISTS biz_activity_scope (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    activity_id BIGINT NOT NULL COMMENT '活动ID',
    scope_type VARCHAR(32) NOT NULL COMMENT '范围类型：STREET/COMMUNITY/COMPLEX/PROPERTY_COMPANY/CUSTOM/ALL',
    scope_ref_id BIGINT NOT NULL COMMENT '范围引用组织ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动可见范围表';

CREATE TABLE IF NOT EXISTS biz_activity_signup (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    activity_id BIGINT NOT NULL COMMENT '活动ID',
    user_id BIGINT NOT NULL COMMENT '报名用户ID',
    signup_status VARCHAR(32) NOT NULL COMMENT '报名状态：SIGNED/CANCELED',
    signup_time DATETIME NOT NULL COMMENT '报名时间',
    cancel_time DATETIME DEFAULT NULL COMMENT '取消报名时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '修改人ID',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删，1已删',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动报名表';
